In [41]:
import torch
import numpy as np 
import pandas as pd 
torch.__version__
    
    
    

'1.0.1.post2'

ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused


In [43]:
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connect

In [40]:
a = torch.ones(2, 3)
b = torch.zeros(3, 3)

torch.cat([a, b], dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused


In [39]:
visdom.__version__

'0.1.8.8'

ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connect